"""empty message

Revision ID: 3958999b057d
Revises: e4829310dda3
Create Date: 2020-10-25 01:56:14.088196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3958999b057d'
down_revision = 'e4829310dda3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pitches_content', table_name='pitches')
    op.create_index(op.f('ix_pitches_content'), 'pitches', ['content'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pitches_content'), table_name='pitches')
    op.create_index('ix_pitches_content', 'pitches', ['content'], unique=True)
    # ### end Alembic commands ###
