"""empty message

Revision ID: 99797c08abdf
Revises: 3958999b057d
Create Date: 2020-10-25 11:18:33.795322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99797c08abdf'
down_revision = '3958999b057d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_pitches_timestamp'), 'pitches', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pitches_timestamp'), table_name='pitches')
    op.drop_column('pitches', 'timestamp')
    # ### end Alembic commands ###
