"""empty message

Revision ID: e4829310dda3
Revises: d6a9537ecb3d
Create Date: 2020-10-25 01:31:16.477855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4829310dda3'
down_revision = 'd6a9537ecb3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categorys_name'), 'categorys', ['name'], unique=False)
    op.add_column('pitches', sa.Column('category', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pitches', 'categorys', ['category'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pitches', type_='foreignkey')
    op.drop_column('pitches', 'category')
    op.drop_index(op.f('ix_categorys_name'), table_name='categorys')
    op.drop_table('categorys')
    # ### end Alembic commands ###
